name = "golddyev/marketplace-sc-old"
version = "0.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'golddyev/marketplace-sc-old'"

[repository]
user = "golddyev"
project = "marketplace-sc-old"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
