name = "koralabs/handles-marketplace-contracts"
version = "0.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'koralabs/handles-marketplace-contracts'"

[repository]
user = "koralabs"
project = "handles-marketplace-contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
