name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18
          check-latest: true

      - name: Update npm and install pnpm
        run: npm install -g npm@latest pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Libssl
        run: |
          wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb

      - name: Install Aiken
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://install.aiken-lang.org | sh
          ~/.aiken/bin/aikup install v1.0.29-alpha
          sudo ln -s ~/.aiken/bin/aiken /usr/local/bin/aiken

      - name: Lint
        run: npm run lint

  aiken-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18
          check-latest: true

      - name: Update npm and install pnpm
        run: npm install -g npm@latest pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Libssl
        run: |
          wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb

      - name: Install Aiken
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://install.aiken-lang.org | sh
          ~/.aiken/bin/aikup install v1.0.29-alpha
          sudo ln -s ~/.aiken/bin/aiken /usr/local/bin/aiken

      - name: Run tests
        run: npm run test:aiken

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18
          check-latest: true

      - name: Update npm and install pnpm
        run: npm install -g npm@latest pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: npm run test
